---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp 
  yum: name={{ item }} state=present
  with_items:
    - ntp
    - libselinux-python

- name: Write ntp configure file
  copy: src=ntp.conf dest=/etc/ntp.conf mode=0755
  notify: restart ntp
  
- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
