---

mariadb_install_pkgs:
  - mariadb
  - mariadb-server
  - MySQL-python
mariadb_config_file: /etc/my.cnf
mariadb_owner: mysql
mariadb_service_name: mariadb
mariadb_bind_address: 127.0.0.1
mariadb_listen_port: 3306
mariadb_data_dir: /data/dbs/mysql


db:
  name: audit
  username: audit_conn
  password: RklInvM7R1a2qV0soB
