---
- name: Copy the issue file to server
  template:
    src: issue.net.j2
    dest: /etc/issue.net
    mode: 0644

- name: Update SSH configuration to be more secure.
  lineinfile:
    dest: "{{ security_ssh_config_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication {{ security_ssh_password_authentication }}"
    - regexp: "^PermitRootLogin"
      line: "PermitRootLogin {{ security_ssh_permit_root_login }}"
    - regexp: "^Port"
      line: "Port {{ security_ssh_port }}"
    - regexp: "^UseDNS"
      line: "UseDNS {{ security_ssh_usedns }}"
    - regexp: "^PermitEmptyPasswords"
      line: "PermitEmptyPasswords {{ security_ssh_permit_empty_password }}"
    - regexp: "^ChallengeResponseAuthentication"
      line: "ChallengeResponseAuthentication {{ security_ssh_challenge_response_auth }}"
    - regexp: "^GSSAPIAuthentication"
      line: "GSSAPIAuthentication {{ security_ssh_gss_api_authentication }}"
    - regexp: "^X11Forwarding"
      line: "X11Forwarding {{ security_ssh_x11_forwarding }}"
    - regexp: "^ClientAliveInterval"
      line: "ClientAliveInterval {{ security_clientaliveinterval }}"
    - regexp: "^ClientAliveCountMax"
      line: "ClientAliveCountMax {{ security_clientalivecountmax }}"
    - regexp: "^IgnoreRhosts"
      line: "IgnoreRhosts {{ security_ignorerhosts }}"
    - regexp: "^HostbasedAuthentication"
      line: "HostbasedAuthentication {{ security_hostbasedauthentication }}"
    - regexp: "^Banner"
      line: "Banner {{ security_banner }}"
  notify: restart ssh
