---

- hosts: 127.0.0.1
  connection: local
  become: yes
  remote_user: root

  roles:
    - check_kernel
    - basic
    - ntp
    - security
    - hugepage
    - redis
    - influxdb
    - mariadb
    - php-fpm
    - nginx
