---

- name: Install the rpm of remi repostory from a remote repo
  yum:
    name: "{{ remi_repo_url }}"
    state: present

- name: Install PHP packages by yum
  yum:
    name: "{{ yum_pkgs }}"
    state: present
  notify: restart php-fpm

- name: Create group
  group:
    name: "{{ owner }}"
    gid: "{{ owner_gid }}"

- name: Create user
  user:
    name: "{{ owner }}"
    uid: "{{ owner_uid }}"
    shell: /sbin/nologin
    createhome: no

- name: Create the directory for php-log
  file:
    path: "{{ php_fpm_log_dir}}"
    state: directory
    mode: 0755
    owner: "{{ owner }}"
    group: "{{ owner }}"

- name: Create the directory for php-session
  file:
    path: "{{ session_dir }}"
    state: directory
    mode: 0755
    owner: "{{ owner }}"
    group: "{{ owner }}"

- name: Write the php.ini file
  template:
    src: php.ini.j2
    dest: "{{ php_ini_file }}"
    mode: 0755
    backup: yes
  notify: restart php-fpm

- name: Write the php-fpm config file
  template:
    src: www.conf.j2
    dest: "{{ php_fpm_file }}"
    mode: 0755
    backup: yes
  notify: restart php-fpm
