---
basic_selinux_file: /etc/selinux/config
basic_selinux_stats: "Disabled"
basic_terminal_timeout: 1800
basic_install_pkgs:
 - libselinux-python
# - libsemanage-python
# - policycoreutils-python
 - wget
 - lrzsz
 - net-tools
 - bash-completion
 - libhugetlbfs
 - bzip2
 - unzip
 - lsof
 - htop
 - mtr
 - vim-enhanced
 - git
 - epel-release
 - python-pip

basic_time_zone: Asia/Shanghai
basic_sysctl_file: /etc/sysctl.conf
basic_sysctl_config_params:
  - fs.file-max = 2097152
  - vm.swappiness = 1
  - vm.dirty_ratio = 60
  - vm.dirty_background_ratio = 2
  - net.ipv4.tcp_synack_retries = 2
  - net.ipv4.ip_local_port_range = 1025 65534
  - net.ipv4.tcp_rfc1337 = 1
  - net.ipv4.tcp_fin_timeout = 15
  - net.ipv4.tcp_keepalive_time = 300
  - net.ipv4.tcp_keepalive_probes = 5
  - net.ipv4.tcp_keepalive_intvl = 15
  - net.core.rmem_default = 31457280
  - net.core.rmem_max = 12582912
  - net.core.wmem_default = 31457280
  - net.core.wmem_max = 12582912
  - net.core.somaxconn = 65535
  - net.core.netdev_max_backlog = 65536
  - net.ipv4.tcp_max_syn_backlog = 65536
  - net.core.optmem_max = 25165824
  - net.ipv4.tcp_mem = 65536 131072 262144
  - net.ipv4.udp_mem = 65536 131072 262144
  - net.ipv4.tcp_rmem = 8192 87380 16777216
  - net.ipv4.udp_rmem_min = 16384
  - net.ipv4.tcp_wmem = 8192 65536 16777216
  - net.ipv4.udp_wmem_min = 16384
  - net.ipv4.tcp_max_tw_buckets = 1440000
  - net.ipv4.tcp_tw_recycle = 1
  - net.ipv4.tcp_tw_reuse = 1
  - net.ipv6.conf.all.disable_ipv6 = 1
  - net.ipv6.conf.default.disable_ipv6 = 1
  - net.ipv6.conf.lo.disable_ipv6 = 1

basic_limited_file: /etc/security/limits.d/10-limited.conf
basic_max_limited_files: 1024000
