---

- name: Install the redis packages
  yum:
    name: "{{ redis_install_pkgs }}"
    state: latest

- name: Setup sysctl
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: Create directory for redis
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ redis_owner }}"
    group: "{{ redis_owner }}"
  with_items:
    - "{{ redis_log_dir }}"
    - "{{ redis_data_dir }}"

- name: Copy the ntp.conf template file
  template:
     src: redis.conf.j2
     dest: "{{ redis_config_file }}"
  notify:
  - restart redis
