---

- name: Install the mariadb packages
  yum: name={{ item }} state=present
  with_items: "{{ mariadb_install_pkgs }}"

- name: Create directory for mariadb
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ mariadb_owner }}"
    group: "{{ mariadb_owner }}"
  with_items:
    - "{{ mariadb_data_dir }}"

- name: Update the mairadb server config file
  template:
    src: my.cnf.j2
    dest: "{{ mariadb_config_file }}"
  notify:
      restart mairadb
