---

- name: Install the mariadb packages
  yum: name={{ item }} state=present
  with_items: "{{ mariadb_install_pkgs }}"

- name: Create directory for mariadb
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ mariadb_owner }}"
    group: "{{ mariadb_owner }}"
  with_items:
    - "{{ mariadb_data_dir }}"

- name: Update the mairadb server config file
  template:
    src: my.cnf.j2
    dest: "{{ mariadb_config_file }}"

- name: Make sure Mysql Service startup
  service:
    name: "{{ mariadb_service_name }}"
    state: restarted
    enabled: yes

- name: Create database
  mysql_db:
      name: "{{ mariadb_name }}"
      state: present
  when: mariadb.name is defined
  ignore_errors: True

- name: Create database user
  mysql_user:
      name: "{{ mariadb_username }}"
      password: "{{ mariadb_password }}"
      priv: "{{ mariadb_name }}.*:ALL"
      host: '127.0.0.1'
      state: present
  when: mariadb_username is defined and mariadb_password is defined
  ignore_errors: True
